---
# tasks file for first_role

- name: make index.html
  file:
    path: /home/ec2-user/Ansible_workbook/test.txt # use to create a file
    state: touch

- name: add line in file
  lineinfile:
    path: /home/ec2-user/Ansible_workbook/test.txt  # use to put some text in the file
    line: "{{ line }}"

- name: add line2 in file
  lineinfile:
    path: /home/ec2-user/Ansible_workbook/test.txt  # use to put some text in the file
    line: "{{ line2 }}"